# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38667fa5d56a39a620b484448cd0def2f9feeee80240fa3b8db573b046b55890183edefc1bd1ab964519c05b4e7e90735d398e6d86412cc2f0c0355a14490d35

test:
  secret_key_base: 6cf5320e1ae2e81a72257b24e54616a54859a6e5c6fe5209ccca2be265bd6fcb72d643265f965fe40e5bcf963f3b6e33a8b4b0ecfa13d95ecc81a4b16c51dedc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
